apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  # The selector defines how we know which pods belong 
  # to this Replication Controller.
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: sunnyvaleit/nginx:1.19.3-openshift
        ports:
        - containerPort: 8081
  replicas: 2