apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      # The port that will be exposed by this service.
      port: 8080
      # Number or name of the port to access on the pods targeted by the service
      targetPort: 8081
  selector:
    app: nginx