apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook-rs
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 2
  # In this case, it’s more or less the same as when we were 
  # creating the ReplicationController, except we’re using 
  # matchExpressions instead of label.
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [guestbook, guest-book, guest_book]}
      - {key: env, operator: NotIn, values: [production]}
  template:
    metadata:
      labels:
        app: guestbook
        env: dev
    spec:
      containers:
      - name: nginx
        image: sunnyvaleit/nginx:1.19.3-openshift