apiVersion: v1
kind: Pod
metadata:
  name: mc1
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: first
    image: sunnyvaleit/nginx:1.19.3-openshift
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: second
    image: debian
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 1;
        done