apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  selector:
    matchLabels:
      run: php-apache
  replicas: 1
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: sunnyvaleit/hpa-example
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        volumeMounts:
        - name: "config"
          mountPath: "/var/www/html/index.php"
          subPath: "index.php"
      restartPolicy: Always
      volumes:
        - name: "config"
          configMap:
            name: "config"
            items:
            - key: index.php
              path: index.php


---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    run: php-apache
spec:
  ports:
  - port: 80
    targetPort: 8081
  selector:
    run: php-apache