apiVersion: v1 
kind: ConfigMap 
metadata:
  name: config
data:
  index.php: |
    <?php
      $x = 0.0001;
      for ($i = 0; $i <= 1000000; $i++) {
        $x += sqrt($x);
      }
      echo "OK!";
    ?>